version: "3.9"

services:
  db:
    image: postgres:16
    container_name: test_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: test-back
    restart: always
    depends_on:
      - db
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/test_db
    command: >
      sh -c "sleep 5 &&
            alembic upgrade head &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  pgdata:
